import { db } from './db.js'
import { TICKER_SPECS } from './ticker.js'

/**
 * A rule book that reads the day and says whether anything happened.
 *
 * Every other view here answers a question somebody asked. This one asks the
 * question itself, once per day, of every source the project has: was that
 * worth reporting? It has to be able to answer no — and to say why, which means
 * naming what it checked and how close the nearest miss came.
 *
 * Nothing here is generated by a language model. The sentences are assembled
 * from fixed parts and measured numbers, because the whole site is precomputed
 * into static files: a model in the delivery path would make the pages
 * unreproducible, and a wrong sentence would be indistinguishable from a right
 * one. Every claim below can be recomputed from the archive.
 *
 * ## One currency for unlike things
 *
 * A calendar-day record, a twelve-day dry spell and an ozone exceedance cannot
 * be compared as they stand. They can be compared by *how often something like
 * them happens*, and one definition of that has to serve them all: every rule
 * reports the number of **days per year on which a statement at least this
 * extreme is true**, taken from this station's own history. "One day in forty
 * years" then outranks "four days a year" without anyone having to declare a
 * category more important than another.
 *
 * The first version of this module mixed two frames — streaks were measured per
 * run and records per calendar day — and the mixture produced nonsense: "the
 * 16th day since the last ice day" was ranked a once-in-two-years event and led
 * an edition dated 31 July, when in truth that is the state of affairs on some
 * three hundred days of every year. Counting days rather than events dissolves
 * the problem without a seasonal special case: a statement that holds on three
 * hundred days a year cannot look rare no matter which day it is made on.
 *
 * That currency also settles the quiet days. Nothing is published above
 * `MAX_PER_YEAR`; if no rule gets under it, the day was ordinary, and the
 * nearest miss is shown to prove the machinery ran.
 */

const DAY = 86_400_000

/** How far back editions are produced. */
const WINDOW_DAYS = 365

/**
 * Rarer than this — in days per year — and it is news.
 *
 * Four days a year is about once a quarter: often enough that a good year still
 * has something to report, rare enough that the ordinary course of the seasons
 * stays out. It also fixes the exchange rate between the categories, because a
 * record for a calendar day happens about 2.4 times a year per quantity and a
 * top-600 daily range about four times — by this currency those really are
 * comparable.
 */
const MAX_PER_YEAR = 4

/**
 * A rule qualifies when it is *strictly* rarer than the bar.
 *
 * The distinction matters: a run that occurred in 141 of 141 years lands at
 * exactly one per year, and reporting a certainty as a finding is the one
 * mistake this newsroom must not make.
 */
const newsworthy = (perYear) => perYear > 0 && perYear < MAX_PER_YEAR

/** No edition carries more than this; the rarest survive. */
const MAX_ITEMS = 8

const MIN_YEARS_FOR_MEAN = 30

/** A partial month needs this share of its days before it may be ranked. */
const MIN_WINDOW_SHARE = 0.9

const MONTHS = [
  'Januar', 'Februar', 'März', 'April', 'Mai', 'Juni',
  'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember',
]

const iso = (date) => `${date.slice(8, 10)}.${date.slice(5, 7)}.${date.slice(0, 4)}`
const dayOf = (date) => `${Number(date.slice(8, 10))}. ${MONTHS[Number(date.slice(5, 7)) - 1]}`
const yearOf = (date) => date.slice(0, 4)

/* -------------------------------------------------------------------------- */
/* What the day is ranked on                                                  */
/* -------------------------------------------------------------------------- */

/**
 * `zero` marks the quantities whose minimum is simply absence: the driest day
 * of a calendar date is almost always one of dozens with no rain at all, and
 * "the 47th-driest 3 July" is not a sentence anybody needs.
 */
const RANK_FIELDS = [
  { key: 'temp_max', label: 'Höchstwert', unit: '°C', decimals: 1, high: 'wärmster', low: 'kältester', accent: 'hot', lowAccent: 'cool' },
  { key: 'temp_min', label: 'Tiefstwert', unit: '°C', decimals: 1, high: 'mildester', low: 'kältester', accent: 'warm', lowAccent: 'cold' },
  { key: 'temp_mean', label: 'Tagesmittel', unit: '°C', decimals: 1, high: 'wärmster', low: 'kältester', accent: 'hot', lowAccent: 'cold' },
  { key: 'precipitation', label: 'Niederschlag', unit: 'mm', decimals: 1, high: 'nassester', low: null, accent: 'wet', zero: true },
  { key: 'wind_max', label: 'Windböe', unit: 'm/s', decimals: 1, high: 'stürmischster', low: null, accent: 'brand', zero: true },
  { key: 'snow', label: 'Schneehöhe', unit: 'cm', decimals: 0, high: 'schneereichster', low: null, accent: 'cool', zero: true },
  { key: 'sunshine', label: 'Sonnenschein', unit: 'h', decimals: 1, high: 'sonnigster', low: null, accent: 'warm', zero: true },
  { key: 'pressure', label: 'Luftdruck', unit: 'hPa', decimals: 1, high: 'höchster', low: 'tiefster', accent: 'brand', lowAccent: 'brand' },
]

/** Derived quantities of a single day, ranked against the whole record. */
const DERIVED = [
  {
    key: 'range',
    label: 'Tagesgang',
    unit: 'K',
    decimals: 1,
    accent: 'dry',
    direction: 'max',
    sentence: (v) => `Ein Tagesgang von ${v} — so weit lagen Höchst- und Tiefstwert auseinander`,
  },
  {
    key: 'jump',
    label: 'Sprung zum Vortag',
    unit: 'K',
    decimals: 1,
    accent: 'hot',
    direction: 'max',
    sentence: (v) => `Das Tagesmittel stieg um ${v} gegenüber dem Vortag`,
  },
  {
    key: 'drop',
    label: 'Sturz zum Vortag',
    unit: 'K',
    decimals: 1,
    accent: 'cold',
    direction: 'max',
    sentence: (v) => `Das Tagesmittel fiel um ${v} gegenüber dem Vortag`,
  },
  {
    key: 'pressure_drop',
    label: 'Druckfall',
    unit: 'hPa',
    decimals: 1,
    accent: 'brand',
    direction: 'max',
    sentence: (v) => `Der Luftdruck fiel binnen 24 Stunden um ${v}`,
  },
]

/* -------------------------------------------------------------------------- */
/* The index                                                                  */
/* -------------------------------------------------------------------------- */

const seriesStmt = db.prepare(`
  SELECT date, year, month, day, strftime('%m-%d', date) AS key,
         temp_mean, temp_max, temp_min, precipitation, wind_max, snow, pressure, sunshine
  FROM daily WHERE station_id = ? ORDER BY date
`)

const cache = new Map()

/** Rank of `value` among `sorted` (ascending), counting from the top. */
function rankFromTop(sorted, value) {
  let better = 0
  for (let i = sorted.length - 1; i >= 0; i--) {
    if (sorted[i] > value) better++
    else break
  }
  return better + 1
}

function rankFromBottom(sorted, value) {
  let better = 0
  for (let i = 0; i < sorted.length; i++) {
    if (sorted[i] < value) better++
    else break
  }
  return better + 1
}

function buildIndex(stationId) {
  const rows = seriesStmt.all(stationId)
  if (rows.length === 0) return null

  const first = rows[0].date
  const last = rows[rows.length - 1].date
  const years = Math.max(
    (Date.parse(`${last}T00:00:00Z`) - Date.parse(`${first}T00:00:00Z`)) / (DAY * 365.2425),
    1,
  )

  /* ---- calendar-day distributions ---------------------------------------- */
  const calendar = new Map()
  for (const field of RANK_FIELDS) calendar.set(field.key, new Map())
  for (const row of rows) {
    for (const field of RANK_FIELDS) {
      const value = row[field.key]
      if (value === null) continue
      const byKey = calendar.get(field.key)
      if (!byKey.has(row.key)) byKey.set(row.key, [])
      byKey.get(row.key).push(value)
    }
  }
  for (const byKey of calendar.values()) for (const list of byKey.values()) list.sort((a, b) => a - b)

  /* ---- calendar-day means, for the anomaly the streaks need --------------- */
  const meanByKey = new Map()
  {
    const byKey = calendar.get('temp_mean')
    for (const [key, list] of byKey) {
      if (list.length < MIN_YEARS_FOR_MEAN) continue
      meanByKey.set(key, list.reduce((a, b) => a + b, 0) / list.length)
    }
  }

  /* ---- derived day quantities -------------------------------------------- */
  let previous = null
  for (const row of rows) {
    const consecutive =
      previous && Date.parse(`${row.date}T00:00:00Z`) - Date.parse(`${previous.date}T00:00:00Z`) === DAY
    row.range = row.temp_max !== null && row.temp_min !== null ? row.temp_max - row.temp_min : null
    const change =
      consecutive && row.temp_mean !== null && previous.temp_mean !== null
        ? row.temp_mean - previous.temp_mean
        : null
    row.jump = change !== null && change > 0 ? change : null
    row.drop = change !== null && change < 0 ? -change : null
    const pressureChange =
      consecutive && row.pressure !== null && previous.pressure !== null
        ? row.pressure - previous.pressure
        : null
    row.pressure_drop = pressureChange !== null && pressureChange < 0 ? -pressureChange : null
    row.anomaly =
      row.temp_mean !== null && meanByKey.has(row.key) ? row.temp_mean - meanByKey.get(row.key) : null
    row.previousDate = consecutive ? previous.date : null
    previous = row
  }

  const derived = new Map()
  for (const spec of DERIVED) {
    const values = rows.map((r) => r[spec.key]).filter((v) => v !== null && Number.isFinite(v))
    values.sort((a, b) => a - b)
    derived.set(spec.key, values)
  }

  /* ---- streaks ------------------------------------------------------------ */
  /**
   * Run lengths, kept twice: at each date, and as one sorted list over every
   * measured day.
   *
   * The second is what the rarity is taken from. Days on which the criterion
   * did not hold enter it as nought, so the rate is a share of all days and not
   * of the days that already agreed with the claim.
   */
  const streaks = new Map()
  for (const spec of TICKER_SPECS) {
    const lengthAt = new Map()
    const dayLengths = []
    const lengths = []
    let run = 0
    let prev = null
    for (const row of rows) {
      const contiguous = prev && Date.parse(`${row.date}T00:00:00Z`) - Date.parse(`${prev.date}T00:00:00Z`) === DAY
      if (prev && !contiguous) {
        if (run > 0) lengths.push(run)
        run = 0
      }
      prev = row
      const value = row[spec.column]
      if (value === null || value === undefined) {
        if (run > 0) lengths.push(run)
        run = 0
        continue
      }
      if (spec.holds(row)) {
        run++
        lengthAt.set(row.date, run)
      } else {
        if (run > 0) lengths.push(run)
        run = 0
      }
      dayLengths.push(spec.holds(row) ? run : 0)
    }
    if (run > 0) lengths.push(run)
    lengths.sort((a, b) => a - b)
    dayLengths.sort((a, b) => a - b)
    streaks.set(spec.key, { lengthAt, dayLengths, lengths })
  }

  /* ---- month-to-date temperature ----------------------------------------- */
  // Cumulative sums per year and month, so a window rank costs one lookup per
  // year instead of a walk over the month.
  const monthly = new Map()
  for (const row of rows) {
    if (row.temp_mean === null) continue
    const key = `${row.month}`
    if (!monthly.has(key)) monthly.set(key, new Map())
    const byYear = monthly.get(key)
    if (!byYear.has(row.year)) byYear.set(row.year, { sum: new Float64Array(32), count: new Int16Array(32) })
    const entry = byYear.get(row.year)
    entry.sum[row.day] = row.temp_mean
    entry.count[row.day] = 1
  }
  for (const byYear of monthly.values()) {
    for (const entry of byYear.values()) {
      for (let d = 1; d <= 31; d++) {
        entry.sum[d] += entry.sum[d - 1]
        entry.count[d] += entry.count[d - 1]
      }
    }
  }

  return {
    stationId,
    rows,
    byDate: new Map(rows.map((r) => [r.date, r])),
    first,
    last,
    years,
    calendar,
    derived,
    streaks,
    monthly,
    germany: germanyIndex(stationId),
    air: airIndex(),
  }
}

/* -------------------------------------------------------------------------- */
/* Germany                                                                    */
/* -------------------------------------------------------------------------- */

const NATIONAL = [
  { key: 'temp_max', direction: 'max', label: 'wärmster Ort Deutschlands', unit: '°C', decimals: 1, accent: 'hot' },
  { key: 'temp_min', direction: 'min', label: 'kältester Ort Deutschlands', unit: '°C', decimals: 1, accent: 'cold' },
  { key: 'precipitation', direction: 'max', label: 'nassester Ort Deutschlands', unit: 'mm', decimals: 1, accent: 'wet' },
  { key: 'wind_max', direction: 'max', label: 'stürmischster Ort Deutschlands', unit: 'm/s', decimals: 1, accent: 'brand' },
]

/**
 * How often this station holds a national extreme, and which days it did.
 *
 * The archive is short — it began on 27 January 2025 — so the rate rests on a
 * year and a half rather than on a century. Every item built from it says so.
 */
function germanyIndex(stationId) {
  const range = db
    .prepare('SELECT MIN(date) AS first, MAX(date) AS last, COUNT(DISTINCT date) AS days FROM germany_daily')
    .get()
  if (!range?.days) return null

  const years = Math.max(range.days / 365.2425, 0.2)
  const holds = new Map()
  const counts = new Map()

  for (const field of NATIONAL) {
    const fn = field.direction === 'max' ? 'MAX' : 'MIN'
    const rows = db
      .prepare(
        `SELECT g.date AS date, g.${field.key} AS value, e.extreme AS extreme
         FROM germany_daily g
         JOIN (SELECT date, ${fn}(${field.key}) AS extreme FROM germany_daily
               WHERE ${field.key} IS NOT NULL GROUP BY date) e ON e.date = g.date
         WHERE g.station_id = ? AND g.${field.key} IS NOT NULL AND g.${field.key} = e.extreme`,
      )
      .all(stationId)
    counts.set(field.key, rows.length)
    for (const row of rows) {
      if (!holds.has(row.date)) holds.set(row.date, [])
      holds.get(row.date).push({ field: field.key, value: row.value })
    }
  }

  const eventRows = db
    .prepare('SELECT date, COUNT(*) AS count FROM record_events GROUP BY date')
    .all()
  const events = new Map(eventRows.map((r) => [r.date, r.count]))
  const eventCounts = eventRows.map((r) => r.count).sort((a, b) => a - b)
  const eventRange = db
    .prepare('SELECT MIN(date) AS first, MAX(date) AS last FROM record_events')
    .get()
  const eventYears = eventRange?.first
    ? Math.max(
        (Date.parse(`${eventRange.last}T00:00:00Z`) - Date.parse(`${eventRange.first}T00:00:00Z`)) /
          (DAY * 365.2425),
        0.2,
      )
    : 1

  return { range, years, holds, counts, events, eventCounts, eventYears, eventRange }
}

/* -------------------------------------------------------------------------- */
/* Air quality                                                                */
/* -------------------------------------------------------------------------- */

/**
 * Only the three limits that are defined on a *day*, and only where the archive
 * is long enough to say how often they are passed.
 *
 * The other environmental series this project keeps — river gauges, pollen,
 * gamma dose rate — are days to weeks old. A rate per year cannot be taken from
 * them, and a newsroom item without a rate would have no place in the ordering.
 * They are named among the limits instead of being quietly left out.
 */
const AIR_RULES = [
  {
    key: 'o3',
    column: 'o3_max8h',
    limit: 120,
    label: 'Ozon',
    text: 'Der Zielwert für Ozon wurde überschritten',
    detail: (v) => `höchster Acht-Stunden-Mittelwert ${v} µg/m³, Zielwert 120`,
    accent: 'warm',
  },
  {
    key: 'no2',
    column: 'no2_max',
    limit: 200,
    label: 'Stickstoffdioxid',
    text: 'Der Stundengrenzwert für Stickstoffdioxid wurde überschritten',
    detail: (v) => `höchster Stundenwert ${v} µg/m³, Grenzwert 200`,
    accent: 'bad',
  },
  {
    key: 'pm10',
    column: 'pm10_mean',
    limit: 50,
    label: 'Feinstaub',
    text: 'Der Tagesgrenzwert für Feinstaub wurde überschritten',
    detail: (v) => `Tagesmittel ${v} µg/m³, Grenzwert 50`,
    accent: 'bad',
  },
]

function airIndex() {
  const range = db
    .prepare('SELECT MIN(date) AS first, MAX(date) AS last, COUNT(DISTINCT date) AS days FROM air_daily')
    .get()
  if (!range?.days) return null

  const years = Math.max(range.days / 365.2425, 0.5)
  const byDate = new Map()
  const counts = new Map()

  for (const rule of AIR_RULES) {
    const rows = db
      .prepare(
        `SELECT date, station, MAX(${rule.column}) AS value FROM air_daily
         WHERE ${rule.column} > ? GROUP BY date`,
      )
      .all(rule.limit)
    counts.set(rule.key, rows.length)
    for (const row of rows) {
      if (!byDate.has(row.date)) byDate.set(row.date, [])
      byDate.get(row.date).push({ rule: rule.key, value: row.value, station: row.station })
    }
  }

  return { range, years, byDate, counts }
}

/* -------------------------------------------------------------------------- */
/* The rules                                                                  */
/* -------------------------------------------------------------------------- */

const fmt = (value, digits) =>
  value === null || value === undefined
    ? '—'
    : value.toLocaleString('de-DE', { minimumFractionDigits: digits, maximumFractionDigits: digits })

function item(fields) {
  return { everyYears: fields.perYear > 0 ? 1 / fields.perYear : null, ...fields }
}

/** Where the day stands among all editions of its own calendar day. */
function calendarItems(index, row) {
  const out = []
  for (const field of RANK_FIELDS) {
    const value = row[field.key]
    if (value === null) continue
    const sorted = index.calendar.get(field.key).get(row.key)
    if (!sorted || sorted.length < 30) continue

    const directions = [
      field.high ? { dir: 'max', rank: rankFromTop(sorted, value), word: field.high, accent: field.accent } : null,
      field.low ? { dir: 'min', rank: rankFromBottom(sorted, value), word: field.low, accent: field.lowAccent } : null,
    ].filter(Boolean)

    for (const entry of directions) {
      // A maximum of nought is the absence of the quantity, not a record in it.
      if (field.zero && entry.dir === 'max' && value <= 0) continue
      // Days per year on which this quantity lands in the top `rank` of its own
      // calendar day: one opportunity per calendar day, 366 of them a year.
      const perYear = (366 * entry.rank) / sorted.length
      out.push(
        item({
          key: `calendar_${field.key}_${entry.dir}`,
          category: 'kalendertag',
          categoryLabel: 'Kalendertag',
          source: 'station',
          accent: entry.accent,
          perYear,
          headline:
            entry.rank === 1
              ? `${cap(entry.word)} ${dayOf(row.date)} seit ${yearOf(index.first)}`
              : `${ordinal(entry.rank, entry.word)} ${dayOf(row.date)} seit ${yearOf(index.first)}`,
          detail: `${field.label} ${fmt(value, field.decimals)} ${field.unit} — Platz ${entry.rank} von ${sorted.length} gemessenen Ausgaben dieses Kalendertages`,
          link: { tab: 'day-in-history', params: { monat: row.month, tag: row.day } },
        }),
      )
    }
  }
  return out
}

/** Single-day quantities that need the neighbouring day or both extremes. */
function derivedItems(index, row) {
  const out = []
  for (const spec of DERIVED) {
    const value = row[spec.key]
    if (value === null || !Number.isFinite(value)) continue
    const sorted = index.derived.get(spec.key)
    if (!sorted || sorted.length < 100) continue

    const rank = rankFromTop(sorted, value)
    const perYear = rank / index.years

    out.push(
      item({
        key: `derived_${spec.key}`,
        category: 'tageswert',
        categoryLabel: 'Tageswert',
        source: 'station',
        accent: spec.accent,
        perYear,
        headline: spec.sentence(`${fmt(value, spec.decimals)} ${spec.unit}`),
        detail: `Das ist Platz ${rank} unter ${sorted.length} Tagen mit dieser Angabe, also ${everyText(perYear)}.`,
        link: { tab: 'yearbook', params: { ansicht: 'kurioses' } },
      }),
    )
  }
  return out
}

/** Runs that were going on that day. */
function streakItems(index, row) {
  const out = []
  for (const spec of TICKER_SPECS) {
    const entry = index.streaks.get(spec.key)
    const length = entry.lengthAt.get(row.date)
    if (!length || length < 2) continue

    // How many days in the whole record carried a run at least this long —
    // days, not runs, because a run of twelve is also a day of eleven, of ten
    // and so on, and the reader is being told about a day.
    let atLeast = 0
    for (let i = entry.dayLengths.length - 1; i >= 0; i--) {
      if (entry.dayLengths[i] >= length) atLeast++
      else break
    }
    const perYear = atLeast / index.years
    if (perYear <= 0) continue

    const record = entry.lengths[entry.lengths.length - 1] ?? length
    out.push(
      item({
        key: `streak_${spec.key}`,
        category: 'serie',
        categoryLabel: spec.family === 'pause' ? 'Pause' : 'Serie',
        source: 'station',
        accent: spec.accent,
        perYear,
        headline: `${length}. Tag: ${spec.label}`,
        detail: `So weit war eine Reihe dieser Art an ${atLeast} von ${index.rows.length} Tagen der Messreihe — ${everyText(perYear)}. Der Rekord liegt bei ${record} Tagen.`,
        link: { tab: 'spells', params: { ansicht: 'ticker' } },
      }),
    )
  }
  return out
}

/** Where the month stood on that day, measured against the same window. */
function monthItem(index, row) {
  const byYear = index.monthly.get(`${row.month}`)
  if (!byYear) return null

  const needed = Math.ceil(row.day * MIN_WINDOW_SHARE)
  const own = byYear.get(row.year)
  if (!own || own.count[row.day] < needed) return null
  const value = own.sum[row.day] / own.count[row.day]

  const others = []
  for (const [year, entry] of byYear) {
    if (year === row.year) continue
    if (entry.count[row.day] < needed) continue
    others.push(entry.sum[row.day] / entry.count[row.day])
  }
  if (others.length < 30) return null

  const warmer = others.filter((v) => v > value).length
  const colder = others.filter((v) => v < value).length
  const total = others.length + 1
  const top = Math.min(warmer, colder) + 1
  // Days per year on which the month to date sits this close to an end of the
  // scale — one opportunity per calendar day, as with the calendar-day ranks.
  const perYear = (366 * top) / total

  const warm = warmer < colder
  return item({
    key: 'month_to_date',
    category: 'monat',
    categoryLabel: 'Monat',
    source: 'station',
    accent: warm ? 'hot' : 'cold',
    perYear,
    headline: `${MONTHS[row.month - 1]} ${row.year} liegt nach ${row.day} Tagen auf Platz ${top} von ${total}${warm ? ' — von warm nach kalt' : ' — von kalt nach warm'}`,
    detail: `Mittel bislang ${fmt(value, 1)} °C, verglichen mit dem 1. bis ${row.day}. ${MONTHS[row.month - 1]} aller anderen Jahre. Was der Monat am Ende wird, steht damit nicht fest.`,
    link: { tab: 'overview', params: { ansicht: 'bilanz', monat: row.month, jahr: row.year } },
  })
}

/** Whether this station held a national extreme, and what fell elsewhere. */
function germanyItems(index, row) {
  const out = []
  const germany = index.germany
  if (!germany) return out

  const holds = germany.holds.get(row.date)
  for (const hit of holds ?? []) {
    const field = NATIONAL.find((f) => f.key === hit.field)
    if (!field) continue
    const perYear = (germany.counts.get(hit.field) ?? 0) / germany.years
    out.push(
      item({
        key: `national_${hit.field}`,
        category: 'deutschland',
        categoryLabel: 'Deutschland',
        source: 'germany',
        accent: field.accent,
        perYear,
        headline: `${cap(field.label)}`,
        detail: `${fmt(hit.value, field.decimals)} ${field.unit} — kein anderer der rund 2.000 meldenden Standorte lag an diesem Tag davor. Gezählt über ein Archiv, das erst am ${iso(germany.range.first)} beginnt.`,
        link: { tab: 'germany', params: { datum: row.date } },
        shortBase: true,
      }),
    )
  }

  const count = germany.events.get(row.date)
  if (count) {
    let atLeast = 0
    for (const value of germany.eventCounts) if (value >= count) atLeast++
    const perYear = atLeast / germany.eventYears
    out.push(
      item({
        key: 'germany_records',
        category: 'deutschland',
        categoryLabel: 'Deutschland',
        source: 'germany',
        accent: 'brand',
        perYear,
        headline: `${count} Allzeitrekord${count === 1 ? '' : 'e'} an deutschen Stationen`,
        detail: `Ein Tag mit so vielen Rekorden kam im Archiv ${atLeast}-mal vor. Dieses Archiv beginnt am ${iso(germany.eventRange.first)}, die Rate ruht also auf gut einem Jahr.`,
        link: { tab: 'records', params: { datum: row.date } },
        shortBase: true,
      }),
    )
  }

  return out
}

/** Limit values passed at the two air-quality stations nearby. */
function airItems(index, row) {
  const out = []
  const air = index.air
  if (!air) return out

  for (const hit of air.byDate.get(row.date) ?? []) {
    const rule = AIR_RULES.find((r) => r.key === hit.rule)
    if (!rule) continue
    const perYear = (air.counts.get(hit.rule) ?? 0) / air.years
    out.push(
      item({
        key: `air_${hit.rule}`,
        category: 'umwelt',
        categoryLabel: 'Umwelt',
        source: 'air',
        accent: rule.accent,
        perYear,
        headline: rule.text,
        detail: `${rule.detail(fmt(hit.value, 0))}. Seit ${iso(air.range.first)} geschah das ${air.counts.get(hit.rule)}-mal, also ${everyText(perYear)}.`,
        link: { tab: 'air', params: {} },
      }),
    )
  }
  return out
}

/* -------------------------------------------------------------------------- */
/* Wording helpers                                                            */
/* -------------------------------------------------------------------------- */

const cap = (text) => text.charAt(0).toUpperCase() + text.slice(1)

/**
 * German writes these as one word: "zweitwärmster", not "zweit wärmster".
 * The superlative is glued on by the caller, which is why nothing here is
 * capitalised until the whole word exists.
 */
const ORDINALS = ['', '', 'zweit', 'dritt', 'viert', 'fünft', 'sechst', 'siebt', 'acht', 'neunt', 'zehnt']
const ordinal = (rank, word) => (ORDINALS[rank] ? cap(ORDINALS[rank] + word) : `${cap(word)} auf Platz ${rank}`)

/** "etwa alle vier Jahre" or "etwa dreimal im Jahr", never "alle 1 Jahre". */
function everyText(perYear) {
  if (!(perYear > 0)) return 'nie zuvor'
  if (perYear >= 1.5) return `etwa ${fmt(perYear, perYear >= 10 ? 0 : 1)}-mal im Jahr`
  if (Math.round(1 / perYear) <= 1) return 'etwa einmal im Jahr'
  return `im Mittel alle ${fmt(1 / perYear, 0)} Jahre`
}

/* -------------------------------------------------------------------------- */
/* The edition                                                                */
/* -------------------------------------------------------------------------- */

function indexFor(stationId) {
  const last = db.prepare('SELECT MAX(date) AS last FROM daily WHERE station_id = ?').get(stationId)
  const cacheKey = `${stationId}|${last?.last ?? ''}`
  if (!cache.has(cacheKey)) cache.set(cacheKey, buildIndex(stationId))
  return cache.get(cacheKey)
}

/** Editions exist for the last year of the archive, newest first. */
export function newsroomDates(stationId) {
  const index = indexFor(stationId)
  if (!index) return []
  return index.rows.slice(-WINDOW_DAYS).map((r) => r.date).reverse()
}

const SOURCE_LABEL = {
  station: 'Messreihe der Station',
  germany: 'Stationsnetz Deutschland',
  air: 'Luftqualität',
}

export function newsroom(stationId, date = null) {
  const index = indexFor(stationId)
  if (!index) return null

  const dates = index.rows.slice(-WINDOW_DAYS).map((r) => r.date)
  const target = date && index.byDate.has(date) ? date : dates[dates.length - 1]
  const row = index.byDate.get(target)

  const candidates = [
    ...calendarItems(index, row),
    ...derivedItems(index, row),
    ...streakItems(index, row),
    ...germanyItems(index, row),
    ...airItems(index, row),
    monthItem(index, row),
  ].filter(Boolean)

  candidates.sort((a, b) => a.perYear - b.perYear)
  const published = candidates.filter((c) => newsworthy(c.perYear))
  const items = published.slice(0, MAX_ITEMS)
  // What came closest without clearing the bar. On a quiet day this is the
  // whole justification: the rules ran, and this is how near the nearest one
  // got.
  const nearest = candidates.find((c) => !newsworthy(c.perYear)) ?? null

  // What the day looked like in plain numbers, so the edition stands on its own.
  const measured = {
    temp_mean: row.temp_mean,
    temp_max: row.temp_max,
    temp_min: row.temp_min,
    precipitation: row.precipitation,
    wind_max: row.wind_max,
    sunshine: row.sunshine,
    snow: row.snow,
    pressure: row.pressure,
    anomaly: row.anomaly,
  }

  return {
    station: stationId,
    date: target,
    label: `${dayOf(target)} ${yearOf(target)}`,
    dates: dates.slice().reverse(),
    range: { first: index.first, last: index.last, years: index.years },
    threshold: MAX_PER_YEAR,
    items,
    dropped: Math.max(published.length - items.length, 0),
    quiet: items.length === 0,
    nearest,
    candidates: candidates.length,
    measured,
    /**
     * The rules that ran, so "nothing happened" can be checked rather than
     * believed. `nearest` is what came closest without clearing the bar.
     */
    checked: {
      calendar: RANK_FIELDS.length,
      derived: DERIVED.length,
      streaks: TICKER_SPECS.length,
      germany: index.germany ? NATIONAL.length + 1 : 0,
      air: index.air ? AIR_RULES.length : 0,
      month: 1,
    },
    sources: [
      {
        key: 'station',
        label: SOURCE_LABEL.station,
        from: index.first,
        to: index.last,
        note: `${Math.round(index.years)} Jahre`,
      },
      index.germany && {
        key: 'germany',
        label: SOURCE_LABEL.germany,
        from: index.germany.range.first,
        to: index.germany.range.last,
        note: `${index.germany.range.days} Tage — die Raten daraus sind grobe Schätzungen`,
      },
      index.air && {
        key: 'air',
        label: SOURCE_LABEL.air,
        from: index.air.range.first,
        to: index.air.range.last,
        note: `${index.air.range.days} Tage`,
      },
    ].filter(Boolean),
    limits: [
      'Flusspegel, Pollenflug und Ortsdosisleistung bleiben außen vor: Diese Reihen sind Tage bis Wochen alt, und ohne Historie lässt sich nicht sagen, wie selten ein Wert ist.',
      'Die bundesweiten Meldungen reichen nicht vor 2025 zurück — für ältere Ausgaben fehlt diese Quelle vollständig.',
    ],
  }
}

/** The single line the dashboard leads with. */
export function newsroomHeadline(stationId) {
  const edition = newsroom(stationId)
  if (!edition) return null
  return {
    date: edition.date,
    label: edition.label,
    quiet: edition.quiet,
    count: edition.items.length,
    dropped: edition.dropped,
    top: edition.items.slice(0, 3).map((entry) => ({
      key: entry.key,
      headline: entry.headline,
      categoryLabel: entry.categoryLabel,
      accent: entry.accent,
      perYear: entry.perYear,
      everyYears: entry.everyYears,
    })),
  }
}
